### PR TITLE
fixes to work with multisite WP installs with networks configured to use subdirectories, as well as SSL sites

### PR DESCRIPTION
**Pull request by joeauty**
fixes to work with multisite WP installs with networks configured to use subdirectories, as well as SSL sites

### CODE REVIEW

**Comment by linickx** [comment]
Hello,

Thanks for the contrib, v.much appreciated!

I'm not sure how this happened.... do you happen to have a diff against version 1.5.3, i.e. the latest trunk (dev) version rather than a diff against /tags/1.5/ ?

Kind Regards,
Nick

**Comment by joeauty** [comment]
Nope, but I can make one. I started working with the copy found here: http://wordpress.org/extend/plugins/root-cookie/ before realizing there even was a trunk or a Github repos. Let me know if you'd like me to get you a diff for 1.5.3...

BTW, you might want to check on the contact form on your site to verify that it works!

**Comment by linickx** [comment]
Please, if you could, I think that this bit is new, but just want to be sure :)

```
if (is_multisite()) {
        // individual user sites in a multi-site install cannot access root cookie options
        // this will not work with subdomain based MU installs
        $domain = $_SERVER['SERVER_NAME'];
    }
```

All wordpress.org plugins have a track repo http://plugins.trac.wordpress.org/browser/root-cookie , as this git hub repo is a mirror I'll copy your contribution into trac/subversion and then re-sync to github.

BTW: the form got fixed on thursday, feel free to test it ;)

Kind Regards,
Nick

**Comment by joeauty** [comment]
That bit is new, but I made a couple of other little tweaky things too. Has your plugin been tested on WP networks/multisite installs? The above code is mostly just a get-in-the-door sort of shim, it can definitely be improved upon.

**Comment by linickx** [comment]
> Has your plugin been tested on WP networks/multisite installs? 

Not by me, possibly by others ;)

The wp_set_auth_cookie function was last updated by WP 3.0.3 which included MU support, so it _should_ work.. I will look to see if WP 3.3 has changed that function, it's probably about time my dev changes made it's way into a release.

rgds,
Nick

**UPDATE** I've [sync'd the code with WP 3.3](http://plugins.trac.wordpress.org/browser/root-cookie/trunk/root-cookie.php) , can you test and let me know the results, if that doesn't fix it I'll look further into your work arounds.

**Comment by joeauty** [comment]
The problem seems to be that multisite cookies created by WordPress use the precise entire FQDN and subdirectory path for the particular site being accessed rather than a generic domain/subdomain or wildcard .domain.com. I believe the WP cookies are created this way because creating a cookie for .domain.com would apply to all sites on the WP network rather than just a single site. A user may want to login to multiple sites, so they should have separate cookies for either site1.domain.com, site2.domain.com, or else domain.com/site1, domain.com/site2 depending on how the network has been setup. Keep in mind that each of these sites will have their own users setup for these too, so cookies ought to be specific to the site they apply to.

You can probably delete my pull request, because on second thought, using Root Cookie with WP network sites probably doesn't make any sense. I was experimenting with tweaking my install to my liking and thought that I could make use of Root Cookie, but I found another way to do what I want :)  I can't really think of a use case where somebody would have a legitimate need for Root Cookie with multisite installs, so it might make sense to disable it altogether for these setups or provide warnings or something. Otherwise, if a user attempts to use Root Cookie with these setups they won't be able to log out of the site they have logged into without manually deleting cookies AFAIC.

**Comment by linickx** [comment]
Thanks for your time Joe, as I don't use MU/Networks/etc this info has been helpful.

Kind Regards,
Nick

**Pull request closed without merging**
